id: I5E4DC07B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:37:00+00:00'
last_modified: '2022-06-08T13:05:03.741682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18491
  title: བདེ་སྨོན་གྱི་འགྲེལ་པ་ཐར་ལམ་བགྲོད་པའི་ཐེམ་སྐས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    76D2:
      image_group_id: I1KG18511
      title: Volume 1 of bde smon gyi 'grel pa thar lam bgrod pa'i them skas/
      total_pages: 618
      order: 1
      base_file: 76D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
