id: P006967
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18491
  title: བདེ་སྨོན་གྱི་འགྲེལ་པ་ཐར་ལམ་བགྲོད་པའི་ཐེམ་སྐས།
  author: ''
  volumes:
    58a24b8203124e04be0248a13530a64c:
      image_group_id: I1KG18511
      title: ''
      volume_number: 1
      total_pages: 618
ebook_metadata:
  title: བདེ་སྨོན་གྱི་འགྲེལ་པ་ཐར་ལམ་བགྲོད་པའི་ཐེམ་སྐས།
  author: ''
  sku: P006967
  cover: cover.jpg
  layers:
  - pagination
